# Generated by Django 6.0.3 on 2026-06-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlogin_duration_auditlogin_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogin',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
