# Generated by Django 6.0.3 on 2026-06-12 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_tipu_fundus_kapital'),
        ('users', '0003_auditlogin_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empdivision',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='empposition',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='empdivision',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empdivision',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empdivision',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empposition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empposition',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlogin',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('funcionario', 'Funcionario'), ('chefe', 'Chefe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?670\\d{7,8}$', 'Format: +6707xxxxxxx')], verbose_name='Nu. Telf.'),
        ),
        migrations.AlterField(
            model_name='empdivision',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.departamento'),
        ),
        migrations.AlterField(
            model_name='empdivision',
            name='dn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.diresaun'),
        ),
        migrations.AlterField(
            model_name='empdivision',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='users.emp'),
        ),
        migrations.AlterField(
            model_name='empdivision',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.gabinete'),
        ),
        migrations.AlterField(
            model_name='empphoto',
            name='emp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='users.emp'),
        ),
        migrations.AlterField(
            model_name='empposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.emp'),
        ),
        migrations.AlterField(
            model_name='empposition',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.position'),
        ),
        migrations.AlterField(
            model_name='empuser',
            name='emp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.emp'),
        ),
        migrations.AlterField(
            model_name='empuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
