# Generated by Django 6.0.3 on 2026-06-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_empdivision_options_alter_empposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
