# Generated by Django 6.0.3 on 2026-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipamember',
            name='role',
            field=models.CharField(choices=[('Xefi', 'Xefi Ekipa'), ('Tekniko', 'Tekniko'), ('Membro', 'Membro')], max_length=10, verbose_name='Funsaun'),
        ),
    ]
