# Generated by Django 6.0.3 on 2026-05-12 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefisiariu', '0001_initial'),
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Naran Negósiu')),
                ('idea', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ideia Negósiu')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('benefisiariu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negosiu', to='benefisiariu.benefisiariu', verbose_name="Benefisiariu / Sira ne'ebé simu")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.category_emp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.sector', verbose_name='Sector Prinsipal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('male', models.IntegerField(default=0, verbose_name='Mane')),
                ('female', models.IntegerField(default=0, verbose_name='Feto')),
                ('total', models.IntegerField(default=0, verbose_name='Total Trabalhador')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kni.business', verbose_name='Negósiu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True, verbose_name='Orsamentu Total')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kni.business', verbose_name='Negósiu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocBussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aldeia', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('area_polygon', models.TextField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('administrativepost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost')),
                ('benefisiariu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locnegosiu', to='benefisiariu.benefisiariu', verbose_name="Benefisiariu / Sira ne'ebé simu")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Montante Aprova')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Montante Apoiu')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('benefisiariu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pnegosiu', to='benefisiariu.benefisiariu', verbose_name="Benefisiariu / Sira ne'ebé simu")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('faze', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.faze', verbose_name='Faze (I, II, III)')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.tipu_programa', verbose_name='Tipu Apoiu')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.status', verbose_name='Estadu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.year', verbose_name='Tinan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
