# Generated by Django 6.0.3 on 2026-05-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locbussiness',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
