# Generated by Django 6.0.3 on 2026-05-18 02:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_tipo_atividade'),
        ('kni', '0002_locbussiness_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('daily_income_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimentu Loron Antes Apoiu ($)')),
                ('monthly_income_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimentu Fulan Antes Apoiu ($)')),
                ('yearly_income_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimentu Tinan Antes Apoiu ($)')),
                ('employee_before', models.IntegerField(default=0, verbose_name='Total Trabalhador Antes Apoiu')),
                ('asset_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Assets Antes Apoiu ($)')),
                ('sales_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Vendas Antes Apoiu ($)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observasaun')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='kni.business', verbose_name='Negósiu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dadus Inisiál Negósiu',
                'verbose_name_plural': 'Dadus Inisiál Negósiu Sira',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fulan')),
                ('monitoring_date', models.DateField(auto_now_add=True, verbose_name='Data Monitorizasaun')),
                ('daily_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimentu Loron ($)')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimentu Fulan ($)')),
                ('yearly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimentu Tinan ($)')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Vendas ($)')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Assets ($)')),
                ('total_employee', models.IntegerField(default=0, verbose_name='Total Trabalhador')),
                ('growth_percentage', models.FloatField(default=0, verbose_name='Percentajen Cresimentu (%)')),
                ('source_data', models.CharField(choices=[('Benefisiariu', 'Benefisiariu'), ('Officer', 'Officer'), ('Survey', 'Survey')], default='Benefisiariu', max_length=20, verbose_name='Fonte Dadus')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verifikadu'), ('Rejected', 'Rejeitadu')], default='Pending', max_length=20, verbose_name='Status Verifikasaun')),
                ('monitoring_status', models.CharField(choices=[('Normal', 'Normal'), ('Risk', 'Risku'), ('Critical', 'Kritiku'), ('Inactive', 'La Ativu')], default='Normal', max_length=20, verbose_name='Status Monitorizasaun')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='monitoring/evidence/', verbose_name='Dokumentu Evidensia')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observasaun')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='kni.business', verbose_name='Negósiu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_monitoring_user', to=settings.AUTH_USER_MODEL, verbose_name='Upload Husi')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.year', verbose_name='Tinan')),
            ],
            options={
                'verbose_name': 'Monitorizasaun Negósiu',
                'verbose_name_plural': 'Monitorizasaun Negósiu Sira',
                'ordering': ['-monitoring_date'],
            },
        ),
    ]
