# Generated by Django 6.0.3 on 2026-05-22 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_tipo_atividade'),
        ('kni', '0003_businessbaseline_businessmonitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmonitoring',
            name='daily_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rendimentu Loron ($)'),
        ),
        migrations.AlterField(
            model_name='businessmonitoring',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rendimentu Fulan ($)'),
        ),
        migrations.AlterField(
            model_name='businessmonitoring',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Assets ($)'),
        ),
        migrations.AlterField(
            model_name='businessmonitoring',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Vendas ($)'),
        ),
        migrations.AlterField(
            model_name='businessmonitoring',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_monitoring_user', to=settings.AUTH_USER_MODEL, verbose_name='Upload Husi'),
        ),
        migrations.AlterField(
            model_name='businessmonitoring',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.year', verbose_name='Tinan'),
        ),
        migrations.AlterField(
            model_name='businessmonitoring',
            name='yearly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rendimentu Tinan ($)'),
        ),
    ]
