# Generated by Django 6.0.3 on 2026-05-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_tipo_atividade'),
        ('kni', '0004_alter_businessmonitoring_daily_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.bussines_size'),
        ),
    ]
