# Generated by Django 6.0.3 on 2026-05-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_tipo_atividade'),
        ('kni', '0005_business_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='t_apoiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.tipu_apoio', verbose_name='Tipu Apoiu'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.tipu_programa', verbose_name='Tipu Programa'),
        ),
    ]
