# Generated by Django 6.0.3 on 2026-05-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_tipo_atividade'),
        ('kni', '0006_program_t_apoiu_alter_program_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naran Negósiu'),
        ),
        migrations.AlterField(
            model_name='business',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.sector', verbose_name='Sector Prinsipal'),
        ),
        migrations.AlterField(
            model_name='program',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montante Apoiu'),
        ),
        migrations.AlterField(
            model_name='program',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montante Aprova'),
        ),
        migrations.AlterField(
            model_name='program',
            name='faze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.faze', verbose_name='Faze (I, II, III)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.status', verbose_name='Estadu'),
        ),
        migrations.AlterField(
            model_name='program',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.year', verbose_name='Tinan'),
        ),
    ]
