# Generated by Django 6.0.3 on 2026-05-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_tipu_fundus_kapital'),
        ('kni', '0007_alter_business_name_alter_business_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='t_fundus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.tipu_fundus_kapital', verbose_name='Tipu Fundus Kapital'),
        ),
    ]
