# Generated by Django 6.0.3 on 2026-05-22 02:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefisiariu', '0002_beneficiariuevaluation'),
        ('custom', '0002_tipo_atividade'),
        ('kni', '0003_businessbaseline_businessmonitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mpmsEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Naran Kompania')),
                ('tinan_hari', models.CharField(blank=True, max_length=4, null=True, verbose_name='Tinan Hari Kompania')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('benefisiariu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpms_empresas', to='benefisiariu.benefisiariu', verbose_name='Benefisiariu')),
                ('business', models.ForeignKey(blank=True, help_text="Opsionál — liga ba Business se benefisiariu ne'e iha ona iha KNI/KS", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpms_empresas', to='kni.business', verbose_name='Negosiu (se iha ona)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tipo_atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.tipo_atividade', verbose_name='Tipo Atividade')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa mpms',
                'verbose_name_plural': 'Empresa mpms Sira',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='mpmsEmpregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nasional_mane', models.IntegerField(default=0, verbose_name='Nasionál Mane')),
                ('nasional_feto', models.IntegerField(default=0, verbose_name='Nasionál Feto')),
                ('internasional_mane', models.IntegerField(default=0, verbose_name='Internasionál Mane')),
                ('internasional_feto', models.IntegerField(default=0, verbose_name='Internasionál Feto')),
                ('total_nasional', models.IntegerField(default=0, verbose_name='Total Nasionál')),
                ('total_internasional', models.IntegerField(default=0, verbose_name='Total Internasionál')),
                ('total_empregador', models.IntegerField(default=0, verbose_name='Total Empregador')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empregador', to='mpms.mpmsempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empregador mpms',
                'verbose_name_plural': 'Empregador mpms Sira',
            },
        ),
        migrations.CreateModel(
            name='mpmsAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipu_apoio', models.CharField(blank=True, choices=[('treinamentu', 'Treinamentu'), ('ekipamentu', 'Ekipamentu'), ('finansiamentu', 'Finansiamentu'), ('konsultoria', 'Konsultória'), ('seluk', 'Seluk')], max_length=20, null=True, verbose_name='Tipu Apoio')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montante Apoio ($)')),
                ('observasaun', models.TextField(blank=True, null=True, verbose_name='Observasaun')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='Opsionál — liga ba Program se registu hanesan iha KNI/KS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpms_atividades', to='kni.program', verbose_name='Programa (se iha ona)')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.status', verbose_name='Estadu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.year', verbose_name='Tinan')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='mpms.mpmsempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Atividade mpms',
                'verbose_name_plural': 'Atividade mpms Sira',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='mpmsKapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kapital_investimento', models.CharField(blank=True, choices=[('0___5000', '< $5,000'), ('5000___30_000', '$5,000 – $30,000'), ('30_000___100_000', '$30,000 – $100,000'), ('100_000_acima', '> $100,000')], max_length=20, null=True, verbose_name='Kapital Investimento')),
                ('tipu_fundus', models.CharField(blank=True, choices=[('home_industria__caseiras', 'Home Industria / Caseiras'), ('mikro', 'Mikro'), ('pequenas', 'Pequenas'), ('medias', 'Médias'), ('grandes', 'Grandes')], max_length=30, null=True, verbose_name='Tipu Fundus Kapital')),
                ('total_fundus', models.CharField(blank=True, choices=[('1___5', '1 – 5'), ('6___20', '6 – 20'), ('21', '21+')], max_length=10, null=True, verbose_name='Total Fundus')),
                ('lukru_brutu_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Lukru Brutu (Kotor) / Mes ($)')),
                ('lukru_brutu_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Lukru Brutu (Kotor) / Ano ($)')),
                ('lukru_likidu_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lukru Likidu (Bersih) / Mes ($)')),
                ('lukru_likidu_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lukru Likidu (Bersih) / Ano ($)')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kapital', to='mpms.mpmsempresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kapital mpms',
                'verbose_name_plural': 'Kapital mpms Sira',
            },
        ),
        migrations.CreateModel(
            name='mpmsLisensamentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lisensamentu', models.CharField(blank=True, choices=[('iha', 'Iha'), ('laiha', 'Laiha'), ('sei_iha_prosesu', 'Sei iha Prosesu')], max_length=20, null=True, verbose_name='Lisensamentu Atividade')),
                ('lisensamentu_status', models.CharField(blank=True, choices=[('valido', 'Válidu'), ('invalidu', 'Inválidu')], max_length=10, null=True, verbose_name='Lisensamentu Atividade Iha')),
                ('tipo_rai', models.CharField(blank=True, choices=[('rai_privado', 'Rai Privadu'), ('rai_aluguer', 'Rai Aluguer'), ('rai_estado', 'Rai Estadu')], max_length=20, null=True, verbose_name='Tipo Propriodade / Rai Halao Atividade')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lisensamentu', to='mpms.mpmsempresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lisensamentu mpms',
                'verbose_name_plural': 'Lisensamentu mpms Sira',
            },
        ),
        migrations.CreateModel(
            name='mpmsLokalizasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aldeia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aldeia')),
                ('rua_avenida', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua / Avenida')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude')),
                ('area_polygon', models.TextField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('administrativepost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.administrativepost', verbose_name='Postu Administrativu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lokalizasaun', to='mpms.mpmsempresa', verbose_name='Empresa')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.municipality', verbose_name='Munisipiu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.village', verbose_name='Suku')),
            ],
            options={
                'verbose_name': 'Lokalizasaun mpms',
                'verbose_name_plural': 'Lokalizasaun mpms Sira',
            },
        ),
        migrations.CreateModel(
            name='mpmsMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kustu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kustu ($) ba Materia Prima')),
                ('origem', models.CharField(blank=True, choices=[('lokal', 'Lokal'), ('internasional', 'Internasionál'), ('kombinasaun', 'Kombinasaun')], max_length=20, null=True, verbose_name="Materia Prima mai husi ne'ebe")),
                ('deskrisaun', models.TextField(blank=True, null=True, verbose_name='Deskrisaun Materia Prima')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materia_prima', to='mpms.mpmsempresa', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materia Prima mpms',
                'verbose_name_plural': 'Materia Prima mpms Sira',
            },
        ),
    ]
