# Generated by Django 6.0.3 on 2026-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpmsempresa',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
