# Generated by Django 6.0.3 on 2026-06-12 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kni', '0008_program_t_fundus'),
        ('mpms', '0002_mpmsempresa_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpmsatividade',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Opsionál Karik Presija', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpms_atividades', to='kni.program', verbose_name='Programa (se iha ona)'),
        ),
    ]
