# Generated by Django 6.0.3 on 2026-05-15 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefisiariu', '0002_beneficiariuevaluation'),
        ('custom', '0002_tipo_atividade'),
        ('kni', '0002_locbussiness_address'),
        ('manufatureira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktividade',
            options={'ordering': ['-year'], 'verbose_name': 'Aktividade', 'verbose_name_plural': 'Aktividade Sira'},
        ),
        migrations.AlterModelOptions(
            name='lokalizasaun',
            options={'verbose_name': 'Lokalizasaun', 'verbose_name_plural': 'Lokalizasaun Sira'},
        ),
        migrations.AlterModelOptions(
            name='manufatur',
            options={'ordering': ['name'], 'verbose_name': 'Manufatura', 'verbose_name_plural': 'Manufatura Sira'},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membro Sira'},
        ),
        migrations.AddField(
            model_name='aktividade',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Opsionál — liga ba Program se registu hanesan iha sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufatur_atividades', to='kni.program', verbose_name='Programa (se iha ona)'),
        ),
        migrations.AddField(
            model_name='manufatur',
            name='business',
            field=models.ForeignKey(blank=True, help_text="Opsionál — liga ba Business se benefisiariu ne'e registu iha KNI/KS/ADI", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufatur_set', to='kni.business', verbose_name='Negosiu (se iha ona)'),
        ),
        migrations.AlterField(
            model_name='aktividade',
            name='industry_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.industrytype'),
        ),
        migrations.AlterField(
            model_name='aktividade',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.status'),
        ),
        migrations.AlterField(
            model_name='aktividade',
            name='support_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.tipu_apoio'),
        ),
        migrations.AlterField(
            model_name='aktividade',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.year'),
        ),
        migrations.AlterField(
            model_name='manufatur',
            name='benefisiariu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufatur_set', to='benefisiariu.benefisiariu', verbose_name='Benefisiariu'),
        ),
        migrations.AlterField(
            model_name='manufatur',
            name='leader_name',
            field=models.CharField(max_length=200, verbose_name='Naran Lider'),
        ),
        migrations.AlterField(
            model_name='manufatur',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Naran Manufatura'),
        ),
        migrations.AlterField(
            model_name='manufatur',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='manufatur',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estadu'),
        ),
    ]
