# Generated by Django 6.0.3 on 2026-05-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kni', '0006_program_t_apoiu_alter_program_program_type'),
        ('manufatureira', '0002_alter_aktividade_options_alter_lokalizasaun_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufatur',
            name='business',
            field=models.ForeignKey(blank=True, help_text="Opsionál — liga ba Business se benefisiariu ne'e registu iha KNI/KS/ADI", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufatur_setes', to='kni.business', verbose_name='Negosiu (se iha ona)'),
        ),
    ]
