# Generated by Django 6.0.3 on 2026-05-24 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatureira', '0003_alter_manufatur_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokalizasaun',
            name='manufatur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lokalidade', to='manufatureira.manufatur'),
        ),
    ]
