# Generated by Django 6.0.3 on 2026-06-02 06:15

import config.upload_utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0003_tipu_fundus_kapital'),
        ('kni', '0008_program_t_fundus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImpactMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_date', models.DateField(verbose_name='Data Monitorizasaun')),
                ('fund_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fundus Simu ($)')),
                ('fund_used', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fundus Uza Ona ($)')),
                ('fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Restante ($)')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rendimentu Fulan Ida ($)')),
                ('monthly_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despeza Fulan Ida ($)')),
                ('monthly_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lukru Fulan Ida ($)')),
                ('total_employee', models.IntegerField(default=0, verbose_name='Total Trabalhador')),
                ('use_accounting_book', models.BooleanField(default=False, verbose_name='Uza Livru Kontabilidade')),
                ('has_income', models.BooleanField(default=True, verbose_name='Iha Rendimentu')),
                ('paid_tax', models.BooleanField(default=False, verbose_name='Selu Impostu')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montante Impostu ($)')),
                ('plan_credit', models.BooleanField(default=False, verbose_name='Planu Atu Simu Kreditu')),
                ('credit_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte Kreditu')),
                ('plan_new_business', models.BooleanField(default=False, verbose_name='Iha Planu Negósiu Foun')),
                ('new_business_idea', models.TextField(blank=True, null=True, verbose_name='Ideia Negósiu Foun')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observasaun')),
                ('hashed', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_monitorings', to='kni.business', verbose_name='Negósiu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitorizasaun Impaktu',
                'verbose_name_plural': 'Monitorizasaun Impaktu Sira',
                'ordering': ['-monitoring_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_name', models.CharField(max_length=255, verbose_name='Naran Asset')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Asset ($)')),
                ('condition', models.CharField(choices=[('Diak', 'Diak'), ('Aat', 'Aat'), ('Lakon', 'Lakon')], default='Diak', max_length=20, verbose_name='Kondisaun')),
                ('hashed', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='monitoring.businessimpactmonitoring', verbose_name='Monitorizasaun')),
            ],
            options={
                'verbose_name': 'Asset Negósiu',
                'verbose_name_plural': 'Asset Negósiu Sira',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateField(verbose_name='Data Transasaun')),
                ('transaction_type', models.CharField(choices=[('IN', 'Osan Tama'), ('OUT', 'Osan Sai')], max_length=10, verbose_name='Tipu Transasaun')),
                ('description', models.CharField(max_length=255, verbose_name='Deskrisaun')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montante ($)')),
                ('hashed', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='monitoring.businessimpactmonitoring', verbose_name='Monitorizasaun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fluxu Osan',
                'verbose_name_plural': 'Fluxu Osan Sira',
            },
        ),
        migrations.CreateModel(
            name='FinancialBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Naran Dokumentu')),
                ('file', models.FileField(upload_to=config.upload_utils.upload_financial_book, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'xlsx', 'xls'])], verbose_name='Anexa Livru Kontabilidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskrisaun')),
                ('hashed', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_books', to='monitoring.businessimpactmonitoring', verbose_name='Monitorizasaun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livru Kontabilidade',
                'verbose_name_plural': 'Livru Kontabilidade Sira',
            },
        ),
        migrations.CreateModel(
            name='FundUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=255, verbose_name='Naran Gastu')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montante ($)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskrisaun')),
                ('hashed', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_usages', to='monitoring.businessimpactmonitoring', verbose_name='Monitorizasaun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilizasaun Fundus',
                'verbose_name_plural': 'Utilizasaun Fundus Sira',
            },
        ),
    ]
