# Generated by Django 6.0.3 on 2026-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (Janeiru - Marsu)'), ('Q2', 'Q2 (Abril - Juñu)'), ('Q3', 'Q3 (Jullu - Setembru)'), ('Q4', 'Q4 (Outubru - Dezembru)')], max_length=2, null=True, verbose_name='Trimestre'),
        ),
    ]
