# Generated by Django 6.0.3 on 2026-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefisiariu', '0002_beneficiariuevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiariuevaluation',
            name='status',
            field=models.CharField(choices=[('Ativu', 'Ativu'), ('Parado', 'Parado'), ('Suspendu', 'Suspendu'), ('Pending', 'Pending')], max_length=20, verbose_name='Status'),
        ),
    ]
