# Generated by Django 6.0.3 on 2026-05-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefisiariu', '0003_alter_beneficiariuevaluation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefisiariu',
            name='email_website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email / Website'),
        ),
        migrations.AddField(
            model_name='benefisiariu',
            name='nivel_edukasaun',
            field=models.CharField(blank=True, choices=[('primaria', 'Primária'), ('pre_secundaria', 'Pré-Secundária'), ('secundaria', 'Secundária'), ('lisensiatura', 'Lisensiatura'), ('mestrado', 'Mestrado'), ('doutoramento', 'Doutoramento'), ('seluk', 'Seluk')], max_length=20, null=True, verbose_name='Nivel Edukasaun'),
        ),
    ]
