# Generated by Django 6.0.3 on 2026-05-29 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefisiariu', '0004_benefisiariu_email_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefisiariuUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefisiariu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefisiariuuser', to='benefisiariu.benefisiariu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Partisipa Treinamentu', 'Partisipa Treinamentu'), ('Pedidu Informasaun', 'Pedidu Informasaun'), ('Reclamasaun', 'Reclamasaun'), ('seluk', 'Seluk')], max_length=90, verbose_name='Tipo Pedidu')),
                ('assuntu', models.CharField(max_length=200, verbose_name='Assuntu')),
                ('deskrisaun', models.TextField(verbose_name='Deskrisaun / Razaun')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('prosesu', 'prosesu'), ('resolvidu', 'resolvidu'), ('rejeita', 'rejeita')], default='pending', max_length=20, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta Officer')),
                ('hashed', models.CharField(blank=True, max_length=128, null=True)),
                ('benefisiariu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidus', to='benefisiariu.benefisiariu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('resolvidu_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resolvidu Husi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedidu',
                'verbose_name_plural': 'Pedidu Sira',
                'ordering': ['-created_at'],
            },
        ),
    ]
