# Generated by Django 6.0.3 on 2026-06-02 06:15

import config.upload_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefisiariu', '0005_benefisiariuuser_pedidu'),
        ('custom', '0003_tipu_fundus_kapital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressorigin',
            options={'verbose_name': 'Endereçu Origem', 'verbose_name_plural': 'Endereçu Origem Sira'},
        ),
        migrations.AlterModelOptions(
            name='addresstl',
            options={'verbose_name': 'Endereçu Timor-Leste', 'verbose_name_plural': 'Endereçu Timor-Leste Sira'},
        ),
        migrations.AlterModelOptions(
            name='beneficiariuevaluation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avaliasaun Benefisiariu', 'verbose_name_plural': 'Avaliasaun Benefisiariu Sira'},
        ),
        migrations.AlterModelOptions(
            name='benefisiariu',
            options={'ordering': ['name'], 'verbose_name': 'Benefisiariu', 'verbose_name_plural': 'Benefisiarius'},
        ),
        migrations.AlterModelOptions(
            name='benefisiariuuser',
            options={'verbose_name': 'User Benefisiariu', 'verbose_name_plural': 'User Benefisiarius'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Foto Sira'},
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diresaun'),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='administrativepost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.administrativepost', verbose_name='Postu Administrativu'),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='aldeia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aldeia'),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.municipality', verbose_name='Municipiu'),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.village', verbose_name='Suku'),
        ),
        migrations.AlterField(
            model_name='beneficiariuevaluation',
            name='hashed',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Data Moris'),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='hashed',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naran Empreza'),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='benefisiariuuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefisiariu_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidu',
            name='hashed',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidu',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prosesu', 'Prosesu'), ('resolvidu', 'Resolvidu'), ('rejeita', 'Rejeita')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='default.png', upload_to=config.upload_utils.upload_photo, verbose_name='Foto'),
        ),
    ]
