# Generated by Django 6.0.3 on 2026-06-03 06:34

import config.upload_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefisiariu', '0006_alter_addressorigin_options_alter_addresstl_options_and_more'),
        ('custom', '0003_tipu_fundus_kapital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressorigin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='addresstl',
            options={},
        ),
        migrations.AlterModelOptions(
            name='beneficiariuevaluation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='benefisiariu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='benefisiariuuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='administrativepost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost'),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='aldeia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality'),
        ),
        migrations.AlterField(
            model_name='addresstl',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village'),
        ),
        migrations.AlterField(
            model_name='beneficiariuevaluation',
            name='hashed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='dob',
            field=models.DateField(null=True, verbose_name='Data Moris'),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='hashed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Naran Empreza'),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='benefisiariu',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.status'),
        ),
        migrations.AlterField(
            model_name='benefisiariuuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidu',
            name='hashed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pedidu',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('prosesu', 'prosesu'), ('resolvidu', 'resolvidu'), ('rejeita', 'rejeita')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='default.png', upload_to=config.upload_utils.upload_photo),
        ),
    ]
